### ISSUE TITLE
bootloader dependencies fail to compile in 0.11.0 and higher

### ISSUE THREAD

**Issue by robertos99** [phil-opp/blog_os#1282]
Transitive dependancies like serde, thiserror, etc. are not linking to the core versions after version 0.11.0 for a no_std environment.
For version 0.10.13 it still works correctly and compiles as expected.

Used rustc: 
❯ rustc --version
rustc 1.77.0-nightly (bf3c6c5be 2024-02-01)

Example error:
```bash
error[E0463]: can't find crate for `std`
 --> /home/robert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.56/src/display.rs:1:5
  |
1 | use std::fmt::Display;
  |     ^^^ can't find crate
  |
  = note: the `x86_64-skuld` target may not support the standard library
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `alloc`
   --> /home/robert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fastrand-2.0.1/src/lib.rs:113:1
    |
113 | extern crate alloc;
    | ^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `std`
 --> /home/robert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/thiserror-1.0.56/src/display.rs:2:5
  |
2 | use std::path::{self, Path, PathBuf};
  |     ^^^ can't find crate
  |
  = note: the `x86_64-skuld` target may not support the standard library
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `std`
 --> /home/robert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fastrand-2.0.1/src/global_rng.rs:5:5
  |
5 | use std::cell::Cell;
  |     ^^^ can't find crate
  |
  = note: the `x86_64-skuld` target may not support the standard library
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
  error[E0412]: cannot find type `Result` in this scope
  --> /home/robert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.196/src/de/seed.rs:13:49
   |
13 |     fn deserialize<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
   |                                                 ^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  + use core::fmt::Result;
   |
1  + use core::result::Result;
   |

error: could not compile `serde` (lib) due to 5106 previous errors

```

**Comment by phil-opp** [comment]
Starting with v0.11, your kernel should depend on `bootloader_api`, not `bootloader` directly. See https://github.com/rust-osdev/bootloader/blob/main/docs/migration/v0.10.md . The `bootloader` crate can then be used from a build script or builder crate to turn your kernel into a bootable disk image.

**Comment by phil-opp** [comment]
I think this should be solved.
