### ISSUE TITLE
`post-02` branch cannot be built successfully

### ISSUE THREAD

**Issue by lima2020-root** [phil-opp/blog_os#1201]
Hi, I cannot build this branch successfully. My environment  and error was listed as following:

```shell
❯ rustc --version --verbose
rustc 1.70.0-nightly (a266f1199 2023-03-22)
binary: rustc
commit-hash: a266f11990d9544ee408e213e1eec8cc9eb032b7
commit-date: 2023-03-22
host: aarch64-apple-darwin
release: 1.70.0-nightly
LLVM version: 15.0.7
```
the dependencies was set as 

```toml
[package]
name = "blog_os"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2021"

[dependencies]
bootloader = "0.11.2"
```

with `#![no_std]` is set in `main.rs`,  running `cargo build`, this `post-02` still tries to find some dependencies and types, like

```shell
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> /Users/XXXX/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/getrandom-0.2.8/src/lib.rs:268:9
    |
268 | /         compile_error!("target is not supported, for more information see: \
269 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /Users/XXXX/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/getrandom-0.2.8/src/lib.rs:290:5
    |
290 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

```

**Comment by bjorn3** [comment]
The post-02 branch uses bootloader 0.9.8, not 0.11.2. The current second edition of blog os doesn't work with bootloader >0.9 as 0.10 and 0.11 use a fundamentally different way of integration. @phil-opp is currently working on a third edition which will use bootloader 0.11.
